version: "3.1"

services:
  db:
    container_name: twitter_db
    image: postgres
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: '$DB_PASSWORD'
      POSTGRES_USER: twitter_dev
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
      #- ./tmp/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  web:
    build: .
    tty: true
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - ./:/app/
